### ISSUE TITLE
add brew formula

### ISSUE THREAD

**Issue by melsman** [diku-dk/smlpkg#2]
Here is a brew formula for smlpkg on Homebrew:

```ruby
class Smlpkg < Formula
  desc "Package manager for Standard ML libraries and programs"
  homepage "https://github.com/diku-dk/smlpkg"
  url "https://github.com/diku-dk/smlpkg/archive/v0.1.3.tar.gz"
  sha256 "cfa7eeff951e04df428694fda38917ee2aaaf0532e2d1dbea7ab4c150f4fe2f0"
  head "https://github.com/diku-dk/smlpkg.git"

  depends_on "mlkit"

  def install
    system "make", "-C", "src", "smlpkg"
    system "make", "install", "INSTALLDIR=#{bin}"
  end

  test do
    (testpath/"sml.pkg.ok").write <<~EOS                                                                        
      package github.com/diku-dk/testpkg                                                                        
                                                                                                                
      require {                                                                                                 
      }                                                                                                         
    EOS                                                                                                         
    system "#{bin}/smlpkg", "init", "github.com/diku-dk/testpkg"
    assert_equal "", shell_output("diff sml.pkg sml.pkg.ok")
  end
end
```

The formula installs fine and `brew audit --new-formula smlpkg` has only one complaint:

```
$ brew audit --new-formula smlpkg
smlpkg:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected
```

Once we get more than 75 stars, we will send a pull request...

**Comment by kfl** [comment]
Shouldn't the brew package be consistent with the nix package?

Currently the nix package by @athas uses `mlton` to build whereas the brew package is build using `mlkit`.

**Comment by athas** [comment]
I don't see why it has to be consistent.  The functional result is the same no matter the compiler, is it not?  The Nix derivation only uses `mlton` because `mlkit` is not in Nixpkgs.

**Comment by athas** [comment]
I'm working on adding `mlkit` to Nixpkgs because why not, but it may take an arbitrary amount of time before it gets in.

**Comment by athas** [comment]
The formula you actually submitted is missing the blank line in the test, which causes it to fail.

**Comment by melsman** [comment]
Is the problem then that diff fails on some systems?

tor. 9. apr. 2020 kl. 22.28 skrev Troels Henriksen <notifications@github.com

**Comment by athas** [comment]
It will fail on *all* systems.  The formula you submitted is not identical to the formula you have shown here.

**Comment by melsman** [comment]
Ahhh - some linting messed up the test!!! I see...

**Comment by athas** [comment]
This is [long since done](https://formulae.brew.sh/formula/smlpkg).

**Comment by frou** [comment]
Is the **mlkit** dependency in smlpkg's brew formula only needed when building from source? i.e. not needed when brew chooses to download a "bottle" (precompiled binary).

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/smlpkg.rb

If that's the case, I think it should be specified as `depends_on "mlkit" => :build`. I can do a PR if you want.

**Comment by athas** [comment]
It is only needed for building, not for running.
