### ISSUE TITLE
How to set a specific directory to install packages to?

### ISSUE THREAD

**Issue by barracuda156** [diku-dk/smlpkg#8]
README just mentions `lib`. How do I specify the path for it?

**Comment by athas** [comment]
It's always `lib` in the current directory.

**Comment by barracuda156** [comment]
@athas You mean wherever I `cd ${dir}` to? Or a directory where `smlpkg` itself is installed?

**Comment by athas** [comment]
From the current directory in the shell when you run `smlpkg`.  Like typing `mkdir lib`.

**Comment by barracuda156** [comment]
Thank you!

**Comment by athas** [comment]
smlpkg's model is not really based around integration with package managers, or even use by non-developers.  Most SML *applications* that make use of smlpkg-based libraries will vendor their dependencies by including the `lib/` directory (either by adding it to source control, or by including it in source distribution releases).
